version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: country_php
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html
    depends_on:
      - mysql
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}

  nginx:
    image: nginx:alpine
    container_name: country_nginx
    restart: unless-stopped
    ports:
      - "8080:80" # Порт, который будет доступен снаружи
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  mysql:
    image: mysql:8.0 # Или другая версия, если нужно
    container_name: country_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: world_countries_db
    ports:
      - "3306:3306" # Порт, если хочешь подключаться снаружи (необязательно)
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d # Автоматически выполнит скрипты при создании контейнера
      - mysql_data:/var/lib/mysql # Для сохранения данных

volumes:
  mysql_data: